export const RL_PREFIX = 'rl' as const;

export const seedTokens = [
  '--rl-accent-50',
  '--rl-font-sans',
  '--rl-font-mono',
  '--rl-radius-control',
  '--rl-radius-surface',
  '--rl-radius-tight',
  '--rl-radius-round',
  '--rl-shadow-color',
  '--rl-motion-fast',
  '--rl-motion-normal',
  '--rl-motion-slow',
  '--rl-motion-exit',
  '--rl-ease-standard',
  '--rl-ease-emphasized',
  '--rl-style-stroke-width',
  '--rl-style-stroke-color',
  '--rl-style-offset-shadow',
  '--rl-style-control-bg',
  '--rl-style-panel-bg',
  '--rl-style-paper-bg',
  '--rl-style-border-radius',
  '--rl-style-background-pattern',
  '--rl-style-focus-shadow',
  '--rl-control-height-sm',
  '--rl-control-height-md',
  '--rl-control-height-lg',
  '--rl-space-1',
  '--rl-space-2',
  '--rl-space-3',
  '--rl-space-4',
  '--rl-space-5'
] as const;

export const semanticTokens = [
  '--rl-color-primary',
  '--rl-color-primary-hover',
  '--rl-color-primary-pressed',
  '--rl-color-primary-focus',
  '--rl-color-primary-muted',
  '--rl-color-danger',
  '--rl-accent-hover-overlay',
  '--rl-accent-ripple',
  '--rl-surface',
  '--rl-surface-raised',
  '--rl-surface-inset',
  '--rl-surface-overlay',
  '--rl-border',
  '--rl-border-strong',
  '--rl-text',
  '--rl-text-muted',
  '--rl-text-inverse',
  '--rl-icon-color',
  '--rl-hover-overlay',
  '--rl-ripple',
  '--rl-focus-ring'
] as const;

export const componentTokens = [
  '--rl-button-bg',
  '--rl-button-fg',
  '--rl-button-border',
  '--rl-button-border-width',
  '--rl-button-radius',
  '--rl-button-shadow',
  '--rl-button-hover-bg',
  '--rl-soft-control-bg',
  '--rl-soft-control-border-width',
  '--rl-soft-control-border-color',
  '--rl-icon-button-size',
  '--rl-chip-bg',
  '--rl-chip-selected-bg',
  '--rl-chip-border-width',
  '--rl-chip-border-color',
  '--rl-chip-radius',
  '--rl-chip-shadow',
  '--rl-input-bg',
  '--rl-input-border',
  '--rl-input-border-width',
  '--rl-input-radius',
  '--rl-input-shadow',
  '--rl-switch-track-bg',
  '--rl-switch-border-width',
  '--rl-switch-border-color',
  '--rl-radio-card-bg',
  '--rl-radio-card-border-width',
  '--rl-radio-card-border-color',
  '--rl-radio-card-radius',
  '--rl-radio-card-shadow',
  '--rl-tab-bg',
  '--rl-tab-border-width',
  '--rl-tab-border-color',
  '--rl-tab-radius',
  '--rl-dialog-bg',
  '--rl-dialog-border-width',
  '--rl-dialog-border-color',
  '--rl-dialog-radius',
  '--rl-dialog-shadow',
  '--rl-drawer-bg',
  '--rl-drawer-border-width',
  '--rl-drawer-border-color',
  '--rl-drawer-shadow',
  '--rl-toast-bg',
  '--rl-toast-border-width',
  '--rl-toast-border-color',
  '--rl-toast-radius',
  '--rl-app-shell-border-width',
  '--rl-app-shell-shadow',
  '--rl-illus-primary',
  '--rl-illus-secondary',
  '--rl-illus-accent',
  '--rl-illus-muted',
  '--rl-illus-line',
  '--rl-illus-bg',
  '--rl-illus-size-sm',
  '--rl-illus-size-md',
  '--rl-illus-size-lg',
  '--rl-empty-gap',
  '--rl-empty-title-color',
  '--rl-empty-description-color',
  '--rl-empty-bg',
  '--rl-empty-border-width',
  '--rl-empty-border-color',
  '--rl-empty-radius',
  '--rl-empty-shadow',
  '--rl-result-title-size',
  '--rl-result-subtitle-size',
  '--rl-result-gap',
  '--rl-result-actions-margin',
  '--rl-result-bg',
  '--rl-result-border-width',
  '--rl-result-border-color',
  '--rl-result-radius',
  '--rl-result-shadow'
] as const;

export type SeedToken = (typeof seedTokens)[number];
export type SemanticToken = (typeof semanticTokens)[number];
export type ComponentToken = (typeof componentTokens)[number];
export type RlToken = SeedToken | SemanticToken | ComponentToken;

export const motion = {
  fast: '120ms',
  normal: '250ms',
  slow: '700ms',
  exit: '150ms',
  standard: 'cubic-bezier(0.19, 1, 0.22, 1)',
  emphasized: 'cubic-bezier(0.1, 0.9, 0.2, 1)'
} as const;

export const breakpoints = {
  compact: 639,
  medium: 800,
  wide: 991
} as const;
