export const NAMI_PREFIX = 'nami' as const;

export const seedTokens = [
  '--nami-accent-50',
  '--nami-font-sans',
  '--nami-font-mono',
  '--nami-radius-control',
  '--nami-radius-surface',
  '--nami-radius-tight',
  '--nami-radius-round',
  '--nami-contrast-level',
  '--nami-shadow-color',
  '--nami-motion-fast',
  '--nami-motion-normal',
  '--nami-motion-slow',
  '--nami-motion-exit',
  '--nami-ease-standard',
  '--nami-ease-emphasized',
  '--nami-style-stroke-width',
  '--nami-style-stroke-color',
  '--nami-style-ink-color',
  '--nami-style-on-paper',
  '--nami-style-on-paper-muted',
  '--nami-style-offset-shadow',
  '--nami-style-control-bg',
  '--nami-style-panel-bg',
  '--nami-style-paper-bg',
  '--nami-style-border-radius',
  '--nami-style-background-pattern',
  '--nami-style-doodle-opacity',
  '--nami-style-paper-line-color',
  '--nami-style-focus-shadow',
  '--nami-control-height-sm',
  '--nami-control-height-md',
  '--nami-control-height-lg',
  '--nami-space-1',
  '--nami-space-2',
  '--nami-space-3',
  '--nami-space-4',
  '--nami-space-5'
] as const;

export const semanticTokens = [
  '--nami-color-primary',
  '--nami-color-primary-hover',
  '--nami-color-primary-pressed',
  '--nami-color-primary-focus',
  '--nami-color-primary-muted',
  '--nami-color-danger',
  '--nami-accent-hover-overlay',
  '--nami-accent-ripple',
  '--nami-surface',
  '--nami-surface-raised',
  '--nami-surface-inset',
  '--nami-surface-overlay',
  '--nami-border',
  '--nami-border-strong',
  '--nami-text',
  '--nami-text-muted',
  '--nami-text-inverse',
  '--nami-icon-color',
  '--nami-hover-overlay',
  '--nami-ripple',
  '--nami-overlay-backdrop',
  '--nami-focus-ring'
] as const;

export const componentTokens = [
  '--nami-button-bg',
  '--nami-button-fg',
  '--nami-button-border',
  '--nami-button-border-width',
  '--nami-button-radius',
  '--nami-button-shadow',
  '--nami-button-hover-bg',
  '--nami-card-bg',
  '--nami-card-fg',
  '--nami-card-inset-bg',
  '--nami-card-border',
  '--nami-card-border-width',
  '--nami-card-radius',
  '--nami-card-shadow',
  '--nami-card-padding',
  '--nami-card-gap',
  '--nami-badge-bg',
  '--nami-badge-fg',
  '--nami-badge-border',
  '--nami-badge-border-width',
  '--nami-badge-radius',
  '--nami-badge-height',
  '--nami-badge-font-size',
  '--nami-badge-padding-x',
  '--nami-soft-control-bg',
  '--nami-soft-control-color',
  '--nami-soft-control-border-width',
  '--nami-soft-control-border-color',
  '--nami-icon-button-size',
  '--nami-chip-bg',
  '--nami-chip-selected-bg',
  '--nami-chip-border-width',
  '--nami-chip-border-color',
  '--nami-chip-radius',
  '--nami-chip-shadow',
  '--nami-input-bg',
  '--nami-input-border',
  '--nami-input-border-width',
  '--nami-input-radius',
  '--nami-input-shadow',
  '--nami-switch-track-bg',
  '--nami-switch-border-width',
  '--nami-switch-border-color',
  '--nami-switch-thumb-bg',
  '--nami-switch-thumb-shadow',
  '--nami-radio-card-bg',
  '--nami-radio-card-border-width',
  '--nami-radio-card-border-color',
  '--nami-radio-card-radius',
  '--nami-radio-card-shadow',
  '--nami-radio-card-selected-shadow',
  '--nami-tab-bg',
  '--nami-tab-border-width',
  '--nami-tab-border-color',
  '--nami-tab-radius',
  '--nami-dialog-bg',
  '--nami-dialog-border-width',
  '--nami-dialog-border-color',
  '--nami-dialog-radius',
  '--nami-dialog-shadow',
  '--nami-drawer-bg',
  '--nami-drawer-border-width',
  '--nami-drawer-border-color',
  '--nami-drawer-shadow',
  '--nami-toast-bg',
  '--nami-toast-border-width',
  '--nami-toast-border-color',
  '--nami-toast-radius',
  '--nami-app-shell-border-width',
  '--nami-app-shell-shadow',
  '--nami-illus-primary',
  '--nami-illus-secondary',
  '--nami-illus-accent',
  '--nami-illus-muted',
  '--nami-illus-line',
  '--nami-illus-bg',
  '--nami-illus-size-sm',
  '--nami-illus-size-md',
  '--nami-illus-size-lg',
  '--nami-empty-gap',
  '--nami-empty-title-color',
  '--nami-empty-description-color',
  '--nami-empty-bg',
  '--nami-empty-border-width',
  '--nami-empty-border-color',
  '--nami-empty-radius',
  '--nami-empty-shadow',
  '--nami-result-title-size',
  '--nami-result-subtitle-size',
  '--nami-result-gap',
  '--nami-result-actions-margin',
  '--nami-result-bg',
  '--nami-result-border-width',
  '--nami-result-border-color',
  '--nami-result-radius',
  '--nami-result-shadow',
  '--nami-spinner-track-color',
  '--nami-transition-progress-height',
  '--nami-page-transition-z-index',
  '--nami-top-progress-height',
  '--nami-top-progress-duration',
  '--nami-top-progress-ease',
  '--nami-top-progress-indeterminate-duration',
  '--nami-top-progress-track-bg',
  '--nami-top-progress-fill-bg',
  '--nami-top-progress-shadow',
  '--nami-top-progress-z-index'
] as const;

export type SeedToken = (typeof seedTokens)[number];
export type SemanticToken = (typeof semanticTokens)[number];
export type ComponentToken = (typeof componentTokens)[number];
export type NamiToken = SeedToken | SemanticToken | ComponentToken;

export const motion = {
  fast: '120ms',
  normal: '250ms',
  slow: '700ms',
  exit: '150ms',
  standard: 'cubic-bezier(0.19, 1, 0.22, 1)',
  emphasized: 'cubic-bezier(0.1, 0.9, 0.2, 1)'
} as const;

export const breakpoints = {
  compact: 639,
  medium: 800,
  wide: 991
} as const;
